version : '3.4'
services:
  bdotnetmvcapp:
    image: jitendra0625/mvcdemo:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - bdotnetwebapi=http://localhost:8080
    ports:
    - 8090:80
    depends_on:
    - bdotnetwebapi
    
  bdotnetwebapi:
    image: jitendra0625/webapidemo:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 8080:80